# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/SoftwareBuild2
    steps:
      # Step 1: Obtain repo from GitHub
      - checkout
      # Step 2: Create a virtual environment and install dependencies
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: Run coding convention software and tests
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest --junitxml=test-results/junit.xml
      # Step 4: Store test results
      - store_test_results:
          path: test-results
      # Step 5: Store test artifacts
      - store_artifacts:
          path: test-results
